#!/usr/bin/env ruby

require 'fileutils'
require 'parsedate'

PACKAGE = 'sysvipc'

version = File.open('VERSION').read.chomp
pv = PACKAGE + '-' + version

# Make directory for building distribution files.

FileUtils.rm_rf(pv)
FileUtils.mkdir(pv)

# Copy files into distribution directory.

File.open('MANIFEST').each do |file|
    file.chomp!
    dir = File.dirname file
    subdir = pv + '/' + dir
    unless File.directory?(subdir)
	FileUtils.mkdir_p(subdir)
    end
    dest = pv + '/' + file
    FileUtils.cp(file, dest)
end

# Make distribution files.

system "tar czf #{pv}.tar.gz #{pv}"

# Clean up.

FileUtils.rm_rf(pv)
