#!/usr/bin/env ruby
#
#    $Source$
#
#    $Revision$
#    $Date$
#
#    Copyright (c) 2006 James Steven Jenkins.
#

require 'sysvipc'
require 'test/unit'

include SystemVIPC

KEY = ftok(__FILE__, 0)

NSEMS = 16
NSEMOPS = 10
NMSGS = 16
SHMSIZE = 1024

class TestCradle < Test::Unit::TestCase

  def setup
  end

  def test_msg

    msg = MessageQueue.new(KEY, IPC_CREAT | 0660)
    assert MessageQueue === msg

    uid = Process.uid
    gid = Process.gid
    perm = Permission.new(msg)
    assert Permission === perm
    assert uid == perm.uid
    assert gid == perm.gid
    assert uid == perm.cuid
    assert gid == perm.cgid

    1.upto(NMSGS) do |i|
      assert msg == msg.send(i, "message #{i}")
    end

    NMSGS.downto(1) do |i|
      assert "message #{i}" == msg.recv(i, 100)
    end

    Process.fork do
      sleep 1
      msg.send(1, "message 1")
    end
    assert "message 1" == msg.recv(1, 100)
    Process.wait

    t = Thread.new do
      sleep 1
      msg.send(2, "message 2")
    end
    assert "message 2" == msg.recv(2, 100)

    msg.remove

  end

  def test_sem

    sem = Semaphore.new(KEY, NSEMS, IPC_CREAT | 0660)
    assert Semaphore === sem

    uid = Process.uid
    gid = Process.gid
    perm = Permission.new(sem)
    assert Permission === perm
    assert uid == perm.uid
    assert gid == perm.gid
    assert uid == perm.cuid
    assert gid == perm.cgid

    assert sem.size == NSEMS

    NSEMS.times do |i|
      assert sem == sem.set_value(i, 2)
      assert 2 == sem.value(i)
    end

    values = Array.new(NSEMS, 1)
    assert sem == sem.set_all(values)
    assert values == sem.to_a

    pid = Process.pid
    NSEMS.times do |i|
      assert pid == sem.pid(i)
      assert 0 == sem.n_count(i)
      assert 0 == sem.z_count(i)
    end

    acquire = []
    release = []
    NSEMOPS.times do |i|
      op = SemaphoreOperation.new(i, -1)
      assert i == op.pos
      assert -1 == op.value
      assert 0 == op.flags
      acquire << op

      op = SemaphoreOperation.new(i, 1)
      assert i == op.pos
      assert 1 == op.value
      assert 0 == op.flags
      release << op
    end

    assert sem == sem.apply(acquire)
    assert sem == sem.apply(release)

    assert sem == sem.apply(acquire)
    Process.fork do
      sem.apply(acquire)
      sem.apply(release)
    end
    sleep 1
    assert sem == sem.apply(release)
    Process.wait

    assert sem == sem.apply(acquire)
    t = Thread.new do
      sem.apply(acquire)
      sem.apply(release)
    end
    sleep 1
    assert sem == sem.apply(release)
    t.join

    sem.remove

  end

  def test_shm

    shm = SharedMemory.new(KEY, SHMSIZE, IPC_CREAT | 0660)
    assert SharedMemory === shm

    uid = Process.uid
    gid = Process.gid
    perm = Permission.new(shm)
    assert Permission === perm
    assert uid == perm.uid
    assert gid == perm.gid
    assert uid == perm.cuid
    assert gid == perm.cgid

    assert SHMSIZE === shm.size

    assert shm == shm.attach

    data_size = SHMSIZE - 1
    adata = 'A' * data_size
    bdata = 'B' * data_size

    assert shm == shm.write(adata)
    assert adata == shm.read(data_size)

    Process.fork do
      shm.write(bdata)
    end
    Process.wait
    assert bdata == shm.read(data_size)

    t = Thread.new do
      shm.write(adata)
    end
    t.join
    assert adata == shm.read(data_size)

    assert shm == shm.detach

    shm.remove

  end

  def teardown
  end

end
